name: Test

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "*.md"

  pull_request:
    paths-ignore:
      - "LICENSE"
      - "*.md"

jobs:
  test:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.frozen
          pip install -r requirements.test.frozen

      - name: Test with pytest
        run: |
          pytest . --junitxml=test-results.xml --cov=create_python_app --cov-report=xml --cov-report=html
