name: Test

on:
  push:
    paths-ignore:
      - "LICENSE"
      - "*.md"

  pull_request:
    paths-ignore:
      - "LICENSE"
      - "*.md"

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]  # "3.4", "3.5", "3.6", "3.7", "3.8", "3.9",

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.frozen
          pip install -r requirements.test.frozen

      - name: Test with pytest
        run: |
          pytest . --doctest-modules --junitxml=junit-test-results.xml --cov=com --cov-report=xml --cov-report=html
